### ISSUE TITLE
Code for Flight School CSP

### ISSUE THREAD

**Issue by EdGonzalez-** [aeroappstechnology/Flight-Scheduler#11]
Code to solve flight school scheduling CSP.  This will be done in Java.  The domain, variables, and constraints can be hard coded for development; later we will implement a method to pull variables (e.g., pilot day off requests) from a database.

For development the results can be output to a text file and do not need to be formatted.  Eventually the results will be inserted into a database so they can be used by the client application.

**Comment by vdmann** [comment]
Dee
