### ISSUE TITLE
Research server space (hosting)

### ISSUE THREAD

**Issue by EdGonzalez-** [aeroappstechnology/Flight-Scheduler#4]
Put together a comparison of server space providers (computing and data storage), with the following considerations:

- [ ]  Can run Java, Node.JS, Python, MySQL, PHP
- [ ]  Ease of installing required tools (e.g., JRE, Node)
- [ ]  Security
- [ ]  Low cost when measured based on GB storage/data transfer and CPU use
- [ ]  Security (DDOS, IP blocking, Firewall, data encryption, etc)

A partial list of alternatives:

- Amazon Web Services EC2 and S3
- Arvixe VPS
- GoDaddy VPS or Dedicated
- Microsoft Azure
- Google Cloud Platform

**Comment by ApertureTS** [comment]
John
