### ISSUE TITLE
Pseudocode Airline Scheduling Scenario

### ISSUE THREAD

**Issue by EdGonzalez-** [aeroappstechnology/Flight-Scheduler#5]
https://capstone-scheduler.slack.com/files/edgonzalez/F0BGJR083/aviation_scheduler_scenarios_for_csp.pdf

**Comment by ApertureTS** [comment]
Dee and Ranil

**Comment by vdmann** [comment]
Ranil and I, have gathered and discussed the basic premise of this scenario defining our variables, constraints, backtracking, Depth-First-Search methods, and mapping out the calendar grid. The next step is to familiarize more of CSP algorithm structure as well as improvements like forward checking and constraint propagation and design of heuristics.
