### ISSUE TITLE
Conceptualize Database Structure

### ISSUE THREAD

**Issue by EdGonzalez-** [aeroappstechnology/Flight-Scheduler#7]
The basic calendaring functionality will consist of allowing a user to determine availability if a resource from a calendar, schedule the resource, and modify the scheduled event as necessary. 

A database will be used to hold all data used to create the schedule.  The purpose of this card is to conceptualize in broad terms how the database will be structured.  Please refer to the Software Requirements Specifications for information about the data that will be handled: https://capstone-scheduler.slack.com/files/edgonzalez/F0BJM4N2Z/specifications.pdf

**Comment by ApertureTS** [comment]
Agustin and I (Derek) are working on this. Should we be able to assign/move these cards? It says "only collaborators can update cards"
